=== Du4lity5151/DestinationSol/engine/src/main/resources/org/destinationsol/assets/schemas/schemaFaction.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Configuration for an in-game faction and the members of the faction.",
  "required": ["name", "description", "colour", "shipDesigns"],
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the faction."
    },
    "description": {
      "type": "string",
      "description": "A string description the faction. This may include an overview of the faction's background."
    },
    "colour": {
      "type": "string",
      "description": "Faction colours are hexadecimal, in the form RRGGBB(AA).",
      "pattern": "^([A-Fa-f0-9]{8}|[A-Fa-f0-9]{6})$"
    },
    "shipDesigns": {
      "type": "array",
      "description": "A list of ship designs that can be produced by this faction.",
      "items": {
        "type": "string",
        "description": "The ResourceUrn of a particular ship.",
        "pattern": "^\\w+:\\w+$"
      }
    },
    "defaultDisposition": {
      "type": "integer",
      "description": "The default disposition that the faction has towards other unknown factions."
    },
    "relations": {
      "type": "object",
      "additionalProperties": { "type": "integer" },
      "description": "Relations between factions."
    }
  }
}

=== Du4lity5151/DestinationSol/modules/core/assets/factions/imperial.json
{
  "name": "Imperial",
  "description": "The Imperial faction has reigned for millennia. Their might is barely contested. Offend at your peril.",
  "colour": "b0c4de",
  "defaultDisposition": 50,
  "shipDesigns": [
    "core:imperialBig",
    "core:imperialCapital",
    "core:imperialMedium",
    "core:imperialSmall",
    "core:imperialTiny",
    "core:station"
  ]
}

=== Du4lity5151/DestinationSol/modules/core/assets/factions/desert.json
{
  "name": "Desert",
  "description": "Masters of camouflage. They also have a strange affinity for mazes.",
  "colour": "624A2E",
  "defaultDisposition": -50,
  "shipDesigns": [
    "core:desertBoss",
    "core:desertMedium",
    "core:desertPlanetTurret",
    "core:desertSmall",
    "core:desertSpaceTurret",
    "core:desertOrbiter"
  ]
}
